// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv4IJM6oEFNxAOGz-4EJLjDh3RfxFCt1Q',
    appId: '1:825780277144:web:3fc395f6830719699e25ed',
    messagingSenderId: '825780277144',
    projectId: 'trackerflutter-8cda3',
    authDomain: 'trackerflutter-8cda3.firebaseapp.com',
    storageBucket: 'trackerflutter-8cda3.firebasestorage.app',
    measurementId: 'G-38P28VMG26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr2_7YmcyTQKNHoZdzQM8v9kph_x4RkSw',
    appId: '1:825780277144:android:ea4892a81ed708829e25ed',
    messagingSenderId: '825780277144',
    projectId: 'trackerflutter-8cda3',
    storageBucket: 'trackerflutter-8cda3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcKe9KfKO5WKTjfEy7LechVuOclpcd_VY',
    appId: '1:825780277144:ios:cd4090981def11739e25ed',
    messagingSenderId: '825780277144',
    projectId: 'trackerflutter-8cda3',
    storageBucket: 'trackerflutter-8cda3.firebasestorage.app',
    iosBundleId: 'ma.esisa.gitTrackerFlutter',
  );
}
